### ISSUE TITLE
README UPDATE 

### ISSUE THREAD

**Issue by akrish4** [Aasthajain123/Mlops_Task#1]
README update by including various open-source programs this project is a part of , like DWOC  

Kindly let me know if you are interested 
Kindly do assign me

**Comment by Aasthajain123** [comment]
Sure
Go ahead!
I will recheck once done
All the best.

**Comment by akrish4** [comment]
thank you @Aasthajain123 
Kindly add the DWOC and Level label and pls assign me

**Comment by Aasthajain123** [comment]
Ya sure!
Updating the same.

**Comment by Aasthajain123** [comment]
I have Assigned.
You can go ahead.

**Comment by akrish4** [comment]
actually its not yet assigned to me 
and pls add the DWOC label also

**Comment by Aasthajain123** [comment]
Done.

**Comment by akrish4** [comment]
still not assigned 
i think you are replying using mail isn't , in github if u check right side of the issue ie above label section , you will find a assign section ,there if you click u will find my name , click on it , that's how you assign one

**Comment by Aasthajain123** [comment]
There was some issue.
Now you can check.
